### ISSUE TITLE
OPPO Find N3 Flip Patch Failed  No needles found in lk.img

### ISSUE THREAD

**Issue by qianmo-xw** [R0rt1z2/lkpatcher#21]
Android Version:13
[root] [INFO] [2024-06-30 19:14:43] MediaTek bootloader (LK) patcher - version: 3.0.0 by R0rt1z2.
[lkpatcher.patcher] [INFO] [2024-06-30 19:14:43] Successfully loaded 5 patches.
[lkpatcher.patcher] [WARNING] [2024-06-30 19:14:43] Skipping invalid needle 2de9f04fadf5ac5d.
[lkpatcher.patcher] [WARNING] [2024-06-30 19:14:43] Skipping invalid needle f0b5adf5925d.
[lkpatcher.patcher] [WARNING] [2024-06-30 19:14:43] Skipping invalid needle 30b583b002ab0022.
[lkpatcher.patcher] [WARNING] [2024-06-30 19:14:43] Skipping invalid needle 08b50a4b7b441b681b68022b.
[lkpatcher.patcher] [WARNING] [2024-06-30 19:14:43] Skipping invalid needle f0b5002489b0.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Lib\site-packages\lkpatcher\__main__.py", line 21, in <module>
    main()
  File "C:\Python312\Lib\site-packages\lkpatcher\main.py", line 56, in main
    image = patcher.patch(args.output)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\lkpatcher\patcher.py", line 157, in patch
    raise NoNeedlesFound(f'No needles found in {self.image.lk_path}.')
lkpatcher.exceptions.NoNeedlesFound: No needles found in lk.img.
[images.zip](https://github.com/user-attachments/files/16044157/images.zip)

**Comment by fyhbauyg** [comment]
> Android Version:13 [root] [INFO] [2024-06-30 19:14:43] MediaTek bootloader (LK) patcher - version: 3.0.0 by R0rt1z2. [lkpatcher.patcher] [INFO] [2024-06-30 19:14:43] Successfully loaded 5 patches. [lkpatcher.patcher] [WARNING] [2024-06-30 19:14:43] Skipping invalid needle 2de9f04fadf5ac5d. [lkpatcher.patcher] [WARNING] [2024-06-30 19:14:43] Skipping invalid needle f0b5adf5925d. [lkpatcher.patcher] [WARNING] [2024-06-30 19:14:43] Skipping invalid needle 30b583b002ab0022. [lkpatcher.patcher] [WARNING] [2024-06-30 19:14:43] Skipping invalid needle 08b50a4b7b441b681b68022b. [lkpatcher.patcher] [WARNING] [2024-06-30 19:14:43] Skipping invalid needle f0b5002489b0. Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Python312\Lib\site-packages\lkpatcher__main__.py", line 21, in main() File "C:\Python312\Lib\site-packages\lkpatcher\main.py", line 56, in main image = patcher.patch(args.output) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\lkpatcher\patcher.py", line 157, in patch raise NoNeedlesFound(f'No needles found in {self.image.lk_path}.') lkpatcher.exceptions.NoNeedlesFound: No needles found in lk.img. [images.zip](https://github.com/user-attachments/files/16044157/images.zip)

你的设备有点特殊，我找不到基址
